// Equipment catalogue data
// Images will be loaded from ./images/ folder
const EQUIPMENT_DATA = [
    // PA Systems
    { id: 'PA-S-01', name: 'Complete PA System Medium', amount: 1, description: 'Professional Meyer Sound PA system for medium venues / 3100W peak power', price: 80, category: 'PA Systems', detailedDescription: 'High-end PA system featuring Meyer Sound professional components designed for demanding medium-sized venues and events. Complete package includes 2× UPA-1P powered loudspeakers, 2× USW-1P powered subwoofers, speaker stands, and comprehensive cabling. Perfect for concerts, live performances, houses of worship, corporate events, and installations requiring exceptional sound quality with high SPL and deep low-frequency extension.\n\nMeyer Sound\'s proprietary DSP processing with built-in crossovers and limiters provides legendary audio precision and protection. Modular design allows flexible configuration for different venue requirements and applications.\n\nIdeal for events up to 100-300 people, concert halls, outdoor festivals, theatrical productions, and touring systems requiring reliable, scalable sound reinforcement with professional-grade performance and Meyer Sound\'s renowned sonic accuracy.' },
    { id: 'PA-S-02', name: 'Complete PA System Medium', amount: 1, description: 'Mid-size PA system for medium venues / 1000W total power', price: 120, category: 'PA Systems', detailedDescription: 'Professional PA system designed for medium-sized venues and events. Complete package includes powered speakers, subwoofer, digital mixer, and comprehensive cabling. Perfect for bands, DJs, corporate events, and installations requiring higher SPL and extended low-frequency response.\n\nDigital mixer with effects and EQ provides professional sound control. Modular design allows flexible configuration for different venue requirements and applications.\n\nIdeal for events up to 200 people, club performances, outdoor festivals, and touring productions requiring reliable, scalable sound reinforcement with professional features.' },
    { id: 'PA-S-03', name: 'Complete PA System Large', amount: 1, description: 'Large-scale PA system for concerts and events / 2000W total power', price: 200, category: 'PA Systems', detailedDescription: 'High-power PA system for large venues, concerts, and festivals. Comprehensive package includes line array elements, powered subwoofers, digital mixing console, stage monitoring, and complete signal processing. Designed for professional touring productions and fixed installations demanding maximum SPL and coverage.\n\nAdvanced digital processing and networking capabilities enable complex multi-zone configurations. Rigging and flying hardware included for permanent and temporary installations.\n\nPerfect for concert halls, outdoor festivals, theaters, and large corporate events up to 500 people requiring professional-grade sound reinforcement with extensive routing and control options.' },
    { id: 'PA-S-04', name: 'Monitor System Complete', amount: 1, description: 'Professional stage monitoring system / wedges and in-ear', price: 60, category: 'PA Systems', detailedDescription: 'Complete stage monitoring solution including powered wedge monitors and wireless in-ear monitoring system. Perfect for bands, theaters, and live performances requiring clear onstage sound for musicians and performers.\n\nMultiple mix capability allows personalized monitoring for each performer. Wireless in-ear system provides freedom of movement while maintaining audio clarity and isolation.\n\nIdeal for professional touring productions, houses of worship, concert venues, and recording studios requiring flexible, high-quality stage monitoring with minimal stage volume and feedback issues.' },
    { id: 'PA-S-05', name: 'Installation PA Package', amount: 1, description: 'Fixed installation PA system for permanent venues / distributed speaker system', price: 150, category: 'PA Systems', detailedDescription: 'Permanent installation PA system designed for fixed venues including restaurants, bars, conference rooms, and retail spaces. Includes distributed ceiling speakers, zone amplification, background music system, and paging capabilities with comprehensive control interface.\n\nMulti-zone capability enables independent control of volume and source for different areas. Installation hardware and mounting brackets included for professional deployment.\n\nPerfect for hotels, conference centers, retail environments, restaurants, and corporate facilities requiring reliable background music and announcement systems with flexible zoning and professional sound quality throughout the venue.' },
    
    // PA Speakers
    { id: 'PA-01', name: 'Meyer Sound UPA-1P', amount: 4, description: 'Wide Coverage Loudspeaker / 60 Hz - 18 kHz / Max Peak SPL 133 dB', price: 50, category: 'PA Speakers', detailedDescription: 'Compact two-way loudspeaker with 12-inch driver and 100° x 40° coverage. Ideal for small to mid-sized venues as main front-of-house speaker or fill speaker in larger systems.\n\nPerfect for theatrical sound reinforcement, houses of worship, concert halls, clubs, portable and installed AV systems, and cinema surround applications.\n\nDelivers uniform coverage with predictable performance and precise imaging for professional sound reinforcement.' },
    { id: 'PA-02', name: 'Meyer Sound USW-1P', amount: 2, description: 'Subwoofer / 35 Hz - 180 Hz / Max Peak SPL 135 dB', price: 50, category: 'PA Speakers', detailedDescription: 'Self-powered subwoofer with two 15-inch drivers delivering flat low-frequency response. Perfect for concert halls, clubs, houses of worship, and theatrical sound reinforcement.\n\nIdeal for surround sound presentations, stage monitoring drum fill, and portable and installed audio-visual systems. Works seamlessly with UPA-1P, UPA-2P and UPJ-1P loudspeakers and other Meyer Sound self-powered systems.\n\nBuilt-in crossover allows simple daisychain distribution for easy setup.' },
    { id: 'PA-03', name: 'Meyer Sound 700-HP', amount: 2, description: 'UltraHigh-Power Subwoofer / 28 – 150 Hz / Max Peak SPL 139 dB', price: 80, category: 'PA Speakers', detailedDescription: 'Ultrahigh-power subwoofer with two 18-inch drivers delivering 2250 watts peak power. Designed for stadiums, arenas, and large concert halls requiring maximum low-frequency headroom and minimal distortion.\n\nPerfect for medium-to-large theatres, clubs, theme parks, and cinema applications demanding extreme bass output with ultimate clarity. Stackable and flyable configuration allows flexible deployment for touring productions and fixed installations.\n\nComplements Meyer Sound loudspeaker systems and line arrays in demanding sound reinforcement applications.' },
    { id: 'PA-04', name: 'Meyer Sound UPM-2P', amount: 4, description: 'Compact Narrow Loudspeaker / 80 Hz – 20 kHz / Max Peak SPL 123 dB', price: 40, category: 'PA Speakers', detailedDescription: 'Ultra-compact self-powered loudspeaker with narrow 45-degree beamwidth for precise coverage control. Perfect for front-fill, under balcony, and delay applications in larger systems.\n\nIdeal for theatrical sound reinforcement, theatre effects, and portable and installed audio-visual systems. Compact design makes it perfect for situations requiring small, inconspicuous speakers with high sound pressure levels and low distortion.\n\nNarrow pattern prevents unwanted reflections and microphone bleed, making it excellent for compact voice reinforcement systems where coverage must be restricted to defined areas.' },
    { id: 'PA-05', name: 'QSC CP8', amount: 4, description: '2-Way Full-Range Active Speaker / 8" & 1.4" / 1000 W peak / 124 dB', price: 20, category: 'PA Speakers', detailedDescription: 'Compact 8-inch two-way active speaker delivering 1000W peak power. Perfect for small to medium venues, corporate events, presentations, and mobile DJ applications.\n\nIdeal for portable sound reinforcement where quick setup and reliability are essential. Lightweight design makes it excellent for touring musicians, event production companies, and rental applications.\n\nWorks great as main PA for smaller venues, monitor wedge, or side-fill speaker. Versatile mounting options allow use as floor monitor or pole-mounted speaker for various configurations.' },
    { id: 'PA-06', name: 'QSC K8.2', amount: 1, description: 'Full Range Active Loudspeaker / 8" & 1.4" / 2000 W peak / 128 dB', price: 20, category: 'PA Speakers', detailedDescription: 'Powerful 8-inch active loudspeaker delivering 2000W peak power with enhanced output and clarity. Perfect for small to medium venues, live performances, and corporate presentations requiring higher SPL than standard compact speakers.\n\nIdeal for mobile entertainers, houses of worship, and installed sound applications. Advanced DSP processing provides optimized sound quality for speech and music reproduction.\n\nVersatile design works as main PA, stage monitor, or delay speaker. Rugged construction and integrated rigging points make it reliable for touring and fixed installation applications.' },
    { id: 'PA-07', name: 'Yamaha Stagepas 300', amount: 1, description: 'Portable Powered PA System / Stage Monitors / 2x150 W', price: 20, category: 'PA Speakers', detailedDescription: 'Compact all-in-one stereo PA system with integrated powered mixer and two 8-inch passive speakers. Perfect for solo performers, small bands, karaoke, corporate presentations, and small venue performances.\n\nBuilt-in reverb and 4 mic/line channels plus 2 stereo channels make it ideal for multi-input applications. Unique storage design allows mixer to stow inside speaker cabinet for ultimate portability. Monitor outputs enable connection to powered stage monitors.\n\nIdeal for mobile entertainers, schools, churches, and anyone needing a complete, portable sound solution with quick setup and minimal transport requirements.' },
    
    // Studio Speakers
    { id: 'SP-01', name: 'Genelec 7350 APM', amount: 1, description: 'Subwoofer / 8" / Peak 104 dB SPL / Power: 150 W / 22 - 120 Hz', price: 40, category: 'Studio Speakers', detailedDescription: 'Compact 8-inch active subwoofer designed for stereo and multichannel monitoring systems. Perfect for studio monitoring, post-production, and multichannel audio installations. Part of our multichannel system configuration alongside Genelec 8330 APM monitors and Fostex 6301B speakers.\n\nExtends low-frequency response down to 22 Hz for accurate bass reproduction in music production, film mixing, and immersive audio applications. Smart Active Monitoring technology integrates seamlessly with Genelec GLM software for room calibration and system optimization.\n\nCompact footprint suits small to medium control rooms, home studios, and mobile production setups.' },
    { id: 'SP-02', name: 'Genelec 8330 APM Pack', amount: 1, description: '2-Way Active Studio Monitors / 45 Hz - 23 kHz / Peak 110 dB', price: 60, category: 'Studio Speakers', detailedDescription: 'Compact two-way active studio monitors with Smart Active Monitoring technology. Perfect for professional music production, mixing, mastering, and broadcast applications.\n\nIdeal for small to medium control rooms, home studios, and mobile recording setups requiring accurate reference monitoring. Part of our multichannel system configuration with Genelec 7350 APM subwoofer and Fostex 6301B speakers. Features advanced DSP with room calibration via GLM software for optimized acoustic performance in any environment.\n\nDelivers precise stereo imaging and extended frequency response for critical listening applications in music production, post-production, and content creation.' },
    { id: 'SP-03', name: 'Fostex 6301B', amount: 10, description: 'Small active speaker / 84 dB / 10W', price: 5, category: 'Studio Speakers', detailedDescription: 'Compact 10cm full-range active speaker designed for multichannel audio systems. Ten speakers available for creating surround sound setups when paired with Genelec 7350 APM subwoofer.\n\nPerfect for electronic music performances, multichannel compositions, immersive audio installations, and experimental sound art. Ideal for any setup requiring multiple small speakers with precise placement.\n\nMagnetically shielded housing allows safe placement near sensitive equipment. Balanced XLR and unbalanced jack inputs provide flexible connectivity for complex multichannel configurations.' },
    
    // Mixers
    { id: 'MX-01', name: 'Allen Heath SQ 5', amount: 1, description: 'Digital Mixer / 48-Channel Digital Mixer', price: 70, category: 'Mixers', detailedDescription: 'Professional 48-channel digital mixer designed for demanding live sound and installation applications. Perfect for medium to large venues, touring productions, theaters, houses of worship, and corporate events requiring extensive input capacity. Features advanced digital processing, built-in FX engines, and comprehensive routing capabilities.\n\nTouchscreen control provides intuitive workflow for complex mixing scenarios. Ideal for concert halls, festivals, conference centers, and multi-room installations. Remote control and app integration enable mixing from anywhere in the venue. Expandable I/O with digital stageboxes suits growing systems.\n\nExcellent for sound engineers requiring professional-grade digital mixing with extensive channel count and flexible configuration options.' },
    { id: 'MX-02', name: 'Allen Heath QU 16', amount: 1, description: 'Digital Mixer / 16 Mono inputs via XLR or jack / 12 Mix outputs', price: 50, category: 'Mixers', detailedDescription: '16-channel digital mixer with intuitive analog-style workflow and touchscreen control. Perfect for live sound reinforcement, installations, and studio recording.\n\nIdeal for bands, theaters, houses of worship, and corporate events transitioning from analog to digital mixing. Features motorized faders, built-in FX engines, and direct multitrack recording via Qu-Drive. Remote control via QU-pad app allows adjustment from anywhere in the venue.\n\n19-inch rack-mountable design suits touring and fixed installations. Excellent for users seeking digital flexibility with familiar analog operation and hands-on control.' },
    { id: 'MX-03', name: 'Allen & Heath AR2412 AudioRack', amount: 1, description: 'Digital Stagebox / 24 XLR mic / 12 XLR line outputs (L/R) / Cat 5', price: 40, category: 'Mixers', detailedDescription: 'Professional digital stagebox with 24 XLR mic inputs and 12 XLR line outputs. Perfect for expanding Allen & Heath digital mixer I/O to the stage, eliminating long analog cable runs.\n\nIdeal for theaters, concert venues, houses of worship, and touring productions requiring clean signal transport from stage to front-of-house. Cat5 connection enables digital audio transmission over long distances with zero signal degradation. Rugged 19-inch rack-mountable design suits both fixed installations and touring applications.\n\nExcellent for multi-room facilities, outdoor festivals, and large venues needing remote I/O expansion. Works seamlessly with Allen & Heath SQ and GLD series mixers for flexible system configurations.' },
    { id: 'MX-04', name: 'Allen & Heath AB168', amount: 1, description: 'Digital Stagebox / 16 XLR mic / 8 XLR line outputs / Cat 5', price: 35, category: 'Mixers', detailedDescription: 'Compact digital stagebox with 16 XLR mic preamps and 8 XLR line outputs designed for GLD and QU series mixers. Perfect for medium-sized live events, theaters, and houses of worship requiring streamlined stage connections.\n\nEthernet connectivity eliminates heavy XLR multicore cables, saving space and weight on tour. Ideal for touring bands, corporate events, and installations where easy setup and cable management are essential. Phantom power indicators provide clear visual feedback for powered microphones.\n\nExcellent for mobile sound engineers and rental companies needing compact, reliable stage I/O expansion. Works seamlessly with Allen & Heath QU-16, QU-24, QU-32, and GLD series digital mixers for flexible system configurations.' },
    { id: 'MX-05', name: 'Yamaha MG12/4', amount: 1, description: '12-Input 4-Bus Mixer', price: 8, category: 'Mixers', detailedDescription: 'Compact 12-channel analog mixer with 4-bus architecture designed for project studios, live sound reinforcement, and video editing applications. Features 6 mono channels with balanced XLR mic inputs and +48V phantom power, plus 3 stereo paired channels for keyboards and playback devices.\n\nPerfect for small bands, recording studios, corporate presentations, and live streaming setups requiring flexible routing. Insert connections on all mono channels enable external processing. Sweepable mid-range EQ with high-pass filter provides precise tonal control. Four output buses include main stereo output and stereo group output for complex signal routing.\n\nIdeal for project studio recording, small live performances, podcasting, and video production requiring reliable analog mixing with professional-grade mic preamps and comprehensive connectivity.' },
    
    // Speaker Stands
    { id: 'ST-SP-01', name: 'K&M 213', amount: 2, description: 'Speaker Stand with Crank Housing', price: 6, category: 'Speaker Stands', detailedDescription: 'Professional heavy-duty steel speaker stand with hand crank mechanism for effortless height adjustment from 138.5 to 218 cm. Supports up to 50 kg centric load. Double-strut tripod legs with replaceable rubber feet provide exceptional stability. Crank mechanism with autolocking system allows smooth height adjustment even with heavy loads. Perfect for large format PA speakers, lighting equipment, and professional installations.' },
    { id: 'ST-SP-02', name: 'K&M 21459 + carry bag', amount: 4, description: '2 x Speaker stands K&M 21450', price: 4, category: 'Speaker Stands', detailedDescription: 'Lightweight aluminum speaker stand set with two K&M 21450 stands and carry bag. Each stand supports up to 40 kg with height adjustment from 127 to 193 cm via ergonomic clamping lever. Weighs only 2.45 kg per stand with additional safety splint for secure hold. Includes 38 mm adapter sleeve and carry bag. Perfect for mobile DJs, bands, corporate events, and portable speaker positioning.' },
    { id: 'ST-SP-03', name: 'Fantek T-102D Stand / Lift', amount: 2, description: 'Wind-up lift / Max. Height: 4.88m, min. H: 2.01m, Max. Load: 100kg', price: 15, category: 'Speaker Stands', detailedDescription: 'Professional three-section telescopic tower lift with wire drive winch system supporting up to 100 kg. Extends from 1.99 to 5.00 meters height. Steel construction with tripod base (2.06 x 2.06 m footprint). Wire drive winch enables smooth height adjustment under load. Adapter accepts 35 mm spigot for truss mounting. Perfect for elevating speakers, lighting trusses, projection screens, and AV equipment at concerts and festivals.' },
    
    // Microphones Dynamic
    { id: 'MI-D-01', name: 'Shure Beta 58 A', amount: 1, description: 'Dynamic Vocal Microphone', price: 6, category: 'Microphones', detailedDescription: 'Professional supercardioid dynamic vocal microphone with enhanced frequency response and neodymium magnet for superior output. Perfect for lead and backing vocals in live performances, studios, and touring applications requiring maximum feedback rejection and vocal clarity.\n\nSupercardioid polar pattern provides exceptional feedback suppression with minimal background noise. Pneumatic shock absorber system eliminates handling noise and vibrations. Optimized transmission range delivers punchy, transparent vocal quality with excellent high-frequency detail. Hardened steel mesh grille and enameled metal body ensure legendary durability.\n\nIdeal for professional singers, touring musicians, houses of worship, concert venues, and studios demanding industry-standard vocal performance. Excellent for Rock, Hip-Hop, Country, and all musical styles requiring powerful, clear vocal reproduction with maximum gain before feedback.' },
    { id: 'MI-D-02', name: 'Shure SM58 LC', amount: 4, description: 'Dynamic Vocal Microphone with Cardioid Directivity', price: 5, category: 'Microphones', detailedDescription: 'The world\'s most popular vocal microphone and legendary industry standard for live performance. Cardioid dynamic microphone designed specifically for professional vocal applications in live sound reinforcement and recording studios. Frequency response from 50Hz-15kHz with presence peak between 2-10kHz delivers warm, clear vocal reproduction. Used by countless artists from clubs to stadiums worldwide for over 50 years.\n\nCardioid polar pattern effectively isolates vocals while minimizing background noise and feedback. Built-in spherical wind and pop filter reduces breath sounds and wind noise. Pneumatic shock mount system eliminates handling noise during energetic performances. Near-indestructible construction with steel mesh grille withstands decades of professional touring abuse. Includes break-resistant stand adapter and zippered carrying bag.\n\nIdeal for lead vocals, backing vocals, spoken word, karaoke, houses of worship, rehearsals, and recording. Excellent for touring musicians, live sound companies, venues, studios, and schools requiring reliable, proven vocal microphone performance. Most recorded and performed-with microphone in history, trusted by professionals and beginners alike.' },
    { id: 'MI-D-03', name: 'Shure SM57 LC', amount: 4, description: 'Dynamic Instrument Microphone', price: 5, category: 'Microphones', detailedDescription: 'Industry-standard cardioid dynamic microphone renowned for versatile instrument and vocal miking. Perfect for professional-quality recording of drums, guitar amplifiers, brass instruments, woodwinds, and live vocals. Handles extreme sound pressure levels without distortion, making it indispensable in studios and on stages worldwide.\n\nContoured frequency response with bass roll-off minimizes proximity effect while 2-6kHz boost provides clarity and transparency. Cardioid polar pattern effectively isolates main sound source while reducing background noise. Pneumatic shock mount system suppresses handling and vibration noise. Near-indestructible construction withstands decades of professional use.\n\nIdeal for snare drums, guitar cabinets, brass sections, saxophone, live vocals, and speech reinforcement. Excellent for recording studios, live sound engineers, touring musicians, and broadcast applications. Trusted by professionals from club stages to presidential podiums for over 50 years.' },
    { id: 'MI-D-04', name: 'Shure PG58', amount: 2, description: 'Dynamic Vocal Microphone', price: 2, category: 'Microphones', detailedDescription: 'Rugged dynamic vocal microphone designed for lead and backup vocal performances. Perfect for live sound reinforcement, karaoke, rehearsals, and budget-conscious productions.\n\nCardioid polar pattern reduces feedback in high-volume settings. Built-in on/off switch provides onstage control. Durable metal construction with hardened steel mesh grille withstands demanding touring and rental applications. Internal shock mount reduces handling noise during active performances.\n\nTailored frequency response optimized specifically for vocal clarity. Ideal for bands, mobile entertainers, houses of worship, schools, and small venues requiring reliable, affordable vocal microphones.' },
    { id: 'MI-D-05', name: 'Shure C606', amount: 1, description: 'Dynamic Vocal Microphone', price: 2, category: 'Microphones', detailedDescription: 'Affordable entry-level dynamic cardioid microphone designed for karaoke, public speaking, and home recording. Perfect for casual vocal performances, presentations, and budget-friendly recording projects.\n\nPronounced midrange with slight upper-mid boost enhances vocal clarity for speech applications. Built-in on/off switch provides convenient control. Durable metal construction with steel mesh grille suits semi-professional and casual live settings.\n\nIdeal for community centers, schools, karaoke venues, small events, and home studio use requiring reliable, cost-effective vocal microphone solutions.' },
    { id: 'MI-D-06', name: 'AKG D880', amount: 1, description: 'Dynamic Vocal / Instrument Microphone', price: 2, category: 'Microphones', detailedDescription: 'Rugged dynamic supercardioid microphone designed for on-stage instrumental and vocal pickup. Perfect for live performances requiring crisp instrumental clarity and improved speech intelligibility.\n\nSupercardioid pattern provides enhanced feedback immunity compared to standard cardioid mics. Ideal for amplified instruments, drum kits, brass sections, and live vocal applications. Very low handling noise through Doubleflex anti-vibration isolation system makes it excellent for active performers.\n\nHigh sensitivity delivers strong output for both vocals and instruments. Perfect for touring bands, live sound reinforcement, club performances, and theater productions requiring versatile, feedback-resistant microphones.' },
    { id: 'MI-D-07', name: 'Shure Beta 52A', amount: 1, description: 'Dynamic Microphone specially optimized for bass drum', price: 7, category: 'Microphones', detailedDescription: 'Professional supercardioid dynamic microphone optimized for bass drums and low-frequency instruments. Handles extreme sound pressure levels up to 174 dB without distortion, perfect for close-miking bass drums, bass amplifiers, tubas, and low-frequency percussion in studio and live applications.\n\nFrequency response emphasizes 50Hz-4kHz range delivering powerful low-end punch with precise attack definition. Modified supercardioid pattern effectively suppresses background noise and feedback. Air-suspended shock mount minimizes impact noise and vibrations. Powerful neodymium magnet requires minimal preamp gain. Integrated stand adapter with XLR connector enables flexible positioning inside bass drums.\n\nIdeal for rock, metal, and jazz drum kits requiring thunderous bass drum presence. Excellent for bass cabinets, kick drum recordings, large PA systems, and touring productions. Often paired with Beta 91A boundary mic for complete bass drum sound. Trusted by professional sound engineers and drummers worldwide.' },
    { id: 'MI-D-08', name: 'Sennheiser E604', amount: 3, description: 'Dynamic Instrument Microphone (Cardioid)', price: 5, category: 'Microphones', detailedDescription: 'Compact cardioid dynamic microphone designed for tom drums, snare, brass, and woodwind instruments. Handles sound pressure levels up to 160 dB without distortion, perfect for close-miking drums and amplified instruments. Glass-fiber reinforced plastic housing weighs only 60 grams while maintaining professional durability.\n\nFrequency response from 40Hz-18kHz with presence boost between 1.5-7kHz delivers punchy, open sound. Included MZH 604 rim clip attaches directly to drum rims for quick, secure positioning without microphone stands. Integrated tripod mount enables versatile placement on rimless drums like djembes and cajons. Hum-compensating coil and low inherent noise ensure clean recordings.\n\nIdeal for multi-mic drum kit setups, percussion recordings, brass sections, and woodwind miking. Excellent for live sound engineers and studios requiring compact, reliable instrument mics. Popular choice for toms, snare bottom, and brass instruments in professional touring and recording applications.' },
    { id: 'MI-D-09', name: 'Sennheiser MD 421 Kompakt', amount: 1, description: 'Dynamic Versatile Microphone (Cardioid)', price: 9, category: 'Microphones', detailedDescription: 'Compact version of the legendary MD 421-II with same renowned capsule in lightweight, streamlined housing. Versatile cardioid dynamic microphone perfect for guitar amplifiers, tom drums, brass instruments, saxophone, vocals, and broadcast applications. Frequency response from 30-17,000Hz with excellent feedback suppression delivers transparent, powerful sound.\n\nRedesigned compact body at 159 grams (half the weight of MD 421-II) enables easy mounting with standard mic clips while maintaining legendary 421 sound quality. Powerful output requires minimal preamp gain. Same proven capsule technology trusted for decades in professional studios and live sound worldwide. Included storage pouch protects investment.\n\nIdeal for recording guitar cabinets, miking toms and snare, brass sections, saxophone, and versatile studio applications. Excellent for sound engineers and musicians requiring professional MD 421 performance in compact, affordable package. Perfect for drum kits, instrument amplifiers, speech, and music production where classic 421 quality is essential.' },
    { id: 'MI-D-10', name: 'Sennheiser EW-D ME2/835-S R1-6', amount: 1, description: 'Digital Wireless System', price: 25, category: 'Microphones', detailedDescription: 'Professional digital wireless system with ME 2-II omnidirectional lavalier microphone and SKM-S handheld transmitter with dynamic MMD 835 cardioid capsule. Frequency range R1-6: 520-576 MHz with 56 MHz switching bandwidth. Audio transmission range 20-20,000 Hz with exceptional 134 dB dynamic range delivers pristine wireless sound quality for professional applications.\n\nDigital transmission with 10 mW power provides reliable performance up to 8 hours on AA batteries. Single-channel receiver with XLR and balanced/unbalanced jack outputs. Smart Assist App enables wireless system settings via mobile device. BNC antenna sockets with included antennas. Rackmount ready with included mounting hardware. 4-digit battery indicator ensures monitoring during performances.\n\nIdeal for live performances, presentations, houses of worship, conferences, and theater productions requiring both handheld vocal and discreet lavalier miking. Excellent for touring musicians, corporate events, broadcasting, and installations demanding professional wireless audio. Includes microphone clamp, power supply with country adapters, and batteries.' },
    
    // Microphones Condenser
    { id: 'MI-C-01', name: 'Beyerdynamic MC 930 Stereo-Set', amount: 1, description: '2 x condenser microphones / Cardioid / 40 - 20,000 Hz', price: 30, category: 'Microphones', detailedDescription: 'Professional stereo-matched pair of cardioid condenser microphones for choir, overhead, and instrument recording. Frequency response 40-20,000 Hz with maximum sound pressure level of 125 dB (140 dB with 15 dB pre-attenuation) handles both delicate acoustic sources and high-SPL applications. Exceptionally low noise and superior clarity compared to vintage alternatives without harshness.\n\nSwitchable 15 dB pre-attenuation pad and 250 Hz low-cut filter enable versatile recording applications. Included EA 19/25 shock mounts provide effective vibration isolation in compact design. Rugged construction with excellent build quality ensures decades of reliable professional use. Stereo-matched for accurate imaging and balanced soundstage. Includes protective case and WS 53 windscreens.\n\nIdeal for acoustic guitar stereo recording, drum overheads, orchestra recording, choir miking, and room ambience capture. Excellent for recording studios, live sound engineers, and classical music applications requiring transparent, detailed sound. Popular choice for acoustic instruments, brass sections, and professional studio work.' },
    { id: 'MI-C-02', name: 'Soundman OKM II Classic/Studio Solo', amount: 1, description: '2 x Electret Microphones / Omnidirectional / 3.5 mm Stereo jack', price: 5, category: 'Microphones', detailedDescription: 'Selected pair of omnidirectional electret binaural microphones for artificial head stereophony and immersive spatial recordings. Worn like earplugs in ears to capture 3D sound exactly as heard by human head. Perfect for field recording, nature recording, street ambience, live concerts, and video recording applications requiring authentic spatial reproduction when played back through headphones.\n\nOperatable with line inputs and battery powered for portable recording with field recorders. Transparent, clear sound with slightly noticeable noise floor for extremely quiet environments but excellent for typical recording situations. Discreet, comfortable in-ear design enables natural head movements during recording. Solid wood storage box and plastic case protect microphones between uses.\n\nIdeal for sound designers, field recordists, documentary producers, ASMR content creators, and musicians capturing immersive concert experiences. Excellent for cathedral recordings, choir documentation, urban soundscapes, and nature recordings. Affordable entry into professional binaural recording technology with results that transport listeners into recorded environments through headphones.' },
    { id: 'MI-C-03', name: 'mikroUši Pro (stereo)', amount: 1, description: 'Stereo high quality omni-directional electret microphones / XLR', price: 5, category: 'Microphones', detailedDescription: 'Pair of phantom-powered stereo-matched high-quality omnidirectional electret microphones with industry-standard XLR connectors for professional field recorders and preamps. Exceptionally low noise and high sensitivity despite tiny 6.8 mm diameter capsules. Perfect for recording delicate sounds, quiet environments, and spatial ambience with remarkable clarity and detail.\n\nSuperior performance compared to built-in recorder microphones with professional-grade specifications. Tiny size enables discreet placement and minimal visual impact during recording. Compatible with pro-sumer and professional recording equipment via XLR phantom power. Earplug-style design allows binaural recording worn in ears for immersive spatial capture.\n\nIdeal for field recordists, sound designers, nature recording, documentary production, and ambient sound capture requiring high-quality portable recording. Excellent for ASMR, location sound, environmental recordings, and situations demanding low-noise, high-sensitivity microphones in ultra-compact form. Professional alternative to consumer-grade binaural microphones with XLR connectivity for serious recording applications.' },
    { id: 'MI-C-04', name: 'Sennheiser MKH 416 P48', amount: 1, description: 'Short gun interference tube microphone / Super-cardioid/lobar', price: 20, category: 'Microphones', detailedDescription: 'Legendary RF condenser shotgun microphone and industry standard for film production since 1970s. Super-cardioid/lobar polar pattern with interference tube design provides exceptional directivity and off-axis rejection for focused sound capture even in noisy environments. Frequency range 40-20,000 Hz with very low self-noise and high sensitivity delivers outstanding speech intelligibility and natural sound quality.\n\nRF condenser design with robust brass housing ensures reliable protection against humidity and moisture for outdoor broadcast applications. Maximum SPL 130 dB captures loud sources without distortion. Balanced floating XLR output without transformer maintains direct audio path. 48V phantom powered. Compact 250 mm length and 165 g weight suits boom pole mounting. Includes MZW 415 windscreen, MZQ 100 mic clamp, and protective case.\n\nIdeal for film dialogue, broadcast interviews, voiceovers, cinematic scenes, Foley work, and instrument miking including hi-hats. Excellent for documentary production, television, outdoor filming, and professional audio requiring dependable shotgun microphone trusted worldwide. Perfect for boom operators, location sound recordists, and filmmakers demanding broadcast-quality speech capture in challenging environments.' },
    { id: 'MI-C-05', name: 'Shure Beta 91A', amount: 1, description: 'Condenser boundary microphone', price: 8, category: 'Microphones', detailedDescription: 'Professional half-cardioid condenser boundary microphone optimized for bass drums, kick drums, pianos, and low-frequency instruments. Combination of Beta 91 and SM 91 designs delivers punchy bass foundation with pronounced 4-9kHz attack definition. Frequency range 20-20,000 Hz handles extreme SPL up to 155 dB without distortion, perfect for powerful bass drum miking and concert grand pianos.\n\nSwitchable two-step contour filter with 400 Hz center frequency reduces unwanted resonances without external EQ. Half-cardioid polar pattern effectively isolates source while minimizing stage bleed. Low-profile boundary design eliminates need for tripod stands - simply place inside bass drum or on piano lid. Robust housing with wire mesh protects capsule from mechanical damage. 11-52V phantom powered. Includes holding eyelets for piano lid mounting.\n\nIdeal for live sound reinforcement, studio bass drum recording, cajón miking, and upright/grand piano applications. Excellent for touring drummers, sound technicians, venues, recording studios, and installations requiring reliable boundary microphone with full bass response and clear attack. Trusted industry standard combining solid workmanship, punchy sound, and spot-on price-performance ratio.' },
    { id: 'MI-C-06', name: 'Beyerdynamic MM 1', amount: 1, description: 'Condenser measurement microphone (omnidirectional)', price: 7, category: 'Microphones', detailedDescription: 'Professional omnidirectional condenser measurement microphone for calibrating sound systems, measuring frequency curves, and analyzing room acoustics. Flat frequency response 20-20,000 Hz with exceptional accuracy ensures trustworthy measurements for PA system tuning, speaker design, and acoustic analysis. Maximum SPL 122 dB with 15 mV/Pa sensitivity provides reliable data across wide dynamic range.\n\nIncludes individual calibration curve file available from Beyerdynamic for precise measurement compensation. Rugged, well-built construction from trusted manufacturer ensures dependable long-term use. 12-48V phantom powered with low 3.4 mA consumption. Compact 133 x 19 mm dimensions with included holder enable versatile positioning. Comes with protective bag and measuring diaphragm. Only 73 g weight suits extended measurement sessions.\n\nIdeal for sound system engineers, PA installers, speaker designers, acousticians, and studio owners requiring accurate acoustic measurements. Excellent for room EQing, feedback elimination, RTA analysis during shows, and professional room calibration with software like Sonarworks. Superior alternative to budget measurement mics with Beyerdynamic reliability and precision for critical audio work.' },
    
    // Microphone Stands
    { id: 'ST-MI-01', name: 'Millenium MS 2004', amount: 10, description: 'Microphone Stand / Height adjustable from 88 - 153 cm', price: 1, category: 'Microphone Stands', detailedDescription: 'Microphone stand with round steel base design for stable positioning without tripod legs spreading on crowded stages. Height adjusts from 88-153 cm via simple twist mechanism, suitable for standing vocalists and most instrument miking applications. Weighs 3.5 kg with 23 cm diameter base providing solid stability.' },
    { id: 'ST-MI-02', name: 'K&M 210/2 Black', amount: 6, description: 'Microphone Stand with adjustable boom arm / height: 900 - 1600 mm', price: 2, category: 'Microphone Stands', detailedDescription: 'Industry-standard professional boom stand from K&M\'s Topline series, unchanged since 1967 with over 2 million units sold worldwide. Die-cast base with folding tripod legs provides exceptional stability. Height adjusts 900-1600 mm with single adjustable tube and 840 mm boom arm for flexible microphone positioning. Sturdy steel construction weighs 3.18 kg, perfect for vocal performances, instrument miking, and overhead drum applications.' },
    { id: 'ST-MI-03', name: 'K&M 25950', amount: 3, description: 'Low microphone stand for bass drums or special use', price: 2, category: 'Microphone Stands', detailedDescription: 'Extra-low microphone stand designed for bass drums and floor-level sound sources. Fixed height of 305 mm with extendable boom arm (425-725 mm) allows precise positioning close to the ground. Heavy 2.8 kg die-cast base with short, sturdy folding legs provides maximum stability in minimal footprint. Ideal for kick drums, guitar amplifiers, and low-positioned instruments.' },
    { id: 'ST-MI-04', name: 'K&M 259', amount: 3, description: 'Microphone stand for drums or special use. Height 425 - 645 mm', price: 2, category: 'Microphone Stands', detailedDescription: 'Half-height microphone stand with telescopic boom arm perfect for drums and low-positioned instruments. Height adjusts 425-645 mm, boom extends 470-775 mm with secure clamping sleeves. Die-cast zinc base with three folding feet ensures stable setup while weighing 2.06 kg. Excellent for snare drums, toms, guitar amplifiers, and any sound source requiring low microphone placement.' },
    { id: 'ST-MI-05', name: 'K&M 21021', amount: 2, description: 'Overhead-Stand / Extra high stand / Adjustable Height: 112 - 201 cm', price: 2, category: 'Microphone Stands', detailedDescription: 'Extra-tall overhead microphone stand designed for drum overheads, choir miking, and elevated sound sources. Height extends 112-201 cm with extra-long 106.5 cm boom arm for maximum reach and flexibility. Heavy-duty construction with wide feet tripod base ensures stability at full extension. Weighs 5.84 kg, ideal for professional stage and studio overhead applications.' },
    { id: 'ST-MI-06', name: 'K&M 210/2 Chrome', amount: 3, description: 'Microphone Stand Height 1050 - 1600 mm', price: 1, category: 'Microphone Stands', detailedDescription: 'Chrome-plated version of K&M\'s industry-standard 210/2 professional boom stand. Same proven design with over 2 million units sold, featuring die-cast base, folding tripod legs, and 840 mm boom arm. Height adjusts 900-1605 mm. Durable chrome finish provides corrosion resistance and elegant appearance for stage performances and studio work.' },
    { id: 'ST-MI-07', name: 'Manfrotto MS0490C Carbon Nanopole Stand', amount: 1, description: 'Lightweight stand / can be used as a boom', price: 4, category: 'Microphone Stands', detailedDescription: 'Ultra-lightweight carbon fiber stand designed for field recording and location work. Weighs only 750 g with maximum height 195 cm, collapsing to 51 cm for transport. Carbon pole removes from base to function as boom pole. Quick-release twist locks enable fast height adjustment. Maximum load 1.5 kg with adjustable leg for uneven terrain. Ideal for portable recording, film production, and lightweight microphone applications.' },
    
    // Audio Recorders & Interfaces
    { id: 'RE-01', name: 'Sound Devices MixPre-3 II', amount: 1, description: 'Audio recorder with USB audio interface / stereo mix + 3 single inputs', price: 25, category: 'Recorders & Interfaces', detailedDescription: 'Professional portable audio recorder with dual functionality as USB audio interface, featuring 5-track recording capability (stereo mix plus 3 individual inputs). Revolutionary 32-bit float recording up to 192 kHz eliminates clipping concerns and provides maximum dynamic range of 142 dB. Premium Kashmir microphone preamps deliver 76 dB gain with exceptional noise floor of -128 dBu, matching studio-grade performance in compact portable format. Built-in timecode generator enables professional video production workflows.\n\nThree XLR mic/line inputs with 48V phantom power, plus stereo 3.5mm aux/mic input provide flexible connectivity for field recording, film production, and podcasting. Per-channel limiter and adjustable low-cut filter (40-160 Hz, 18 dB/octave) ensure clean recordings in challenging environments. Records to SD/SDHC/SDXC cards up to 512 GB with simultaneous USB backup capability. Functions as 5-in/2-out USB-C audio interface for studio use. Free Wingman app enables wireless remote control.\n\nIdeal for filmmakers requiring two-mic-and-boom setups, sound designers needing portable professional recording, broadcast journalists, podcasters, and musicians capturing live performances. Compact 144 x 110 x 36 mm dimensions weigh only 480 g without batteries. Flexible powering via 4 AA batteries, USB bus power, or included AC adapter ensures reliable operation in any location. Exceptional preamp quality and 32-bit float technology make this the go-to choice for professionals demanding uncompromising audio quality on location.' },
    { id: 'RE-02', name: 'Zoom H2n', amount: 1, description: 'Portable WAV/MP3 Recorder', price: 5, category: 'Recorders & Interfaces', detailedDescription: 'Versatile portable recorder with five built-in microphones and four recording modes including MS stereo, 90° X/Y stereo, and 2-channel/4-channel surround. Perfect for field recording, podcasting, live concert recording, and ambient sound capture.\n\nIdeal for musicians, sound designers, journalists, and content creators needing portable multi-mic recording. Records up to 24-bit/96kHz WAV or MP3 directly to SD card. Built-in effects including compression/limiting and MS decoding. USB audio interface functionality enables direct recording to computer.\n\nExcellent for location recording, documentary production, nature recording, rehearsal documentation, and mobile journalism. Compact design with over 20 hours battery life suits extended field work and travel recording applications.' },
    { id: 'RE-03', name: 'Motu UltraLite MK3', amount: 1, description: 'USB audio interface / 10 inputs & 14 outputs', price: 15, category: 'Recorders & Interfaces', detailedDescription: 'Versatile compact audio interface offering hybrid FireWire/USB2 connectivity with professional audio quality up to 192 kHz sample rates. Comprehensive I/O includes 10 inputs (2 mic/instrument, 6 line-level analog, stereo S/PDIF) and 14 outputs (10 analog, stereo S/PDIF, stereo headphone) housed in rugged half-rack enclosure. Premium mic preamps deliver clean gain for studio and stage applications. MIDI I/O enables connection of keyboards, controllers, and sound modules.\n\nPowerful on-board CueMix FX DSP mixer provides zero-latency monitoring with professional effects processing independent of computer CPU. Classic Reverb offers lengths up to 60 seconds, 7-band parametric EQ models British analog console characteristics, and dual compression options include conventional compressor plus Leveler (LA-2A optical compressor emulation) for vintage musical gain control. Intuitive cross-platform software provides graphic mixing, parametric EQ editing, and advanced analysis tools including real-time FFT, spectrogram waterfall, oscilloscope, and phase analysis displays.\n\nPerfect for project studios, mobile recording rigs, and live performance setups requiring flexible connectivity and professional sound quality. Functions as standalone mixer with effects when disconnected from computer - all parameters adjustable via front-panel backlit LCD. Compatible with Mac and Windows via WDM/ASIO/Core Audio drivers, works seamlessly with all major DAW software. Includes AudioDesk workstation software for Mac with 24-bit recording/editing and 32-bit mixing/processing. Exceptional value for musicians, producers, and engineers needing reliable multi-channel interface with premium preamps and built-in mixing capabilities.' },
    
    // DI Boxes
    { id: 'DI-01', name: 'BSS Audio AR133', amount: 2, description: 'Active DI Box (Battery/ Phantom Powered)', price: 6, category: 'DI Boxes', detailedDescription: 'Professional active DI box with industry-standard performance and iconic curved design allowing easy stacking and cable routing underneath. XLR and 6.3mm jack inputs with link output, balanced XLR output with ground lift, and switchable pad (-20/-40 dB) provide comprehensive connectivity options. Galvanic isolation ensures clean signal transfer. Operates on 9V battery or 48V phantom power for flexible use. Renowned for exceptional sound quality, transparency, and rugged construction. Widely used in professional touring and studio applications for instruments, keyboards, and line-level sources.' }, 
    { id: 'DI-02', name: 'Millenium DI-33', amount: 3, description: 'Active DI Box (Battery/Phantom)', price: 2, category: 'DI Boxes', detailedDescription: 'Budget-friendly active DI box offering professional features at affordable price point. XLR and jack inputs with link output featuring -20 dB pad switch, balanced XLR output, ground lift, and galvanic isolation. Wide frequency range 10-40,000 Hz ensures full-spectrum signal transfer. Powered by 9V battery or phantom power. Sturdy metal housing with corner protectors provides reliable protection for stage and studio use. Excellent value for musicians, small venues, and rental companies needing dependable DI boxes without premium cost.' },
    { id: 'DI-03', name: 'Palmer PAN 04', amount: 1, description: 'Passive Stereo DI-Box', price: 5, category: 'DI Boxes', detailedDescription: 'High-quality passive stereo DI box with 2-channel capability for keyboards, stereo effects, and dual-source applications. Jack inputs, balanced XLR outputs, switchable pad (0 dB/-30 dB), and ground lift switches on both channels. Input impedance 68 ohm, output impedance 600 ohm, transfer ratio 10:1, maximum output level +4 dBu. No battery or phantom power required - purely transformer-based design delivers transparent, musical sound. Tank-like build quality with protected buttons. 5-year manufacturer warranty. Ideal for keyboards, stereo playback sources, and professional installations requiring reliable passive signal conversion.' },
    { id: 'DI-04', name: 'Radial Engineering Pro 48', amount: 1, description: 'Active DI Box', price: 5, category: 'DI Boxes', detailedDescription: 'Professional active DI box from Radial\'s acclaimed Pro series featuring phantom-powered operation (48V required). Jack input/thru and balanced XLR output with -15 dB pad and ground/lift switch. Robust steel book-style chassis provides exceptional durability for touring applications. Linear frequency response with low THD and plenty of headroom delivers pristine signal quality. Excellent for guitar, bass, and line-level sources in studio recording and live performance. Simple, reliable design with professional-grade components ensures consistent performance. Industry-standard choice for engineers requiring uncompromising sound quality and rugged construction.' },
    
    // Cables
    { 
        id: 'CA-01', 
        name: 'XLR + XLR', 
        amount: 15,
        price: 0.30,
        description: 'Microphone Cable / 3-pin', 
        category: 'Cables',
        detailedDescription: 'Professional balanced XLR microphone cables with 3-pin XLR male to female connectors for connecting microphones, speakers, and audio equipment. Available in 3m, 6m, 10m, and 20m lengths.',
        variants: [
            { length: '3m', amount: 15, price: 0.30 },
            { length: '6m', amount: 21, price: 0.40 },
            { length: '10m', amount: 19, price: 0.50 },
            { length: '20m', amount: 5, price: 0.80 }
        ]
    },
    { id: 'CA-05', name: 'XLR (male) + 6.3mm stereo jack', amount: 13, description: 'XLR (male) + 6.3mm stereo jack', price: 0.50, category: 'Cables', detailedDescription: 'Balanced 6m audio cable with XLR male to 6.3mm stereo TRS jack for connecting mixer outputs to powered speakers, effects processors, or studio monitors.' },
    { id: 'CA-06', name: 'XLR (female) + 6.3mm stereo jack', amount: 16, description: 'XLR (female) + 6.3mm stereo jack', price: 0.40, category: 'Cables', detailedDescription: 'Balanced 6m audio cable with XLR female to 6.3mm stereo TRS jack for connecting keyboards, drum machines, or outboard gear to mixer inputs.' },
    { id: 'CA-07', name: 'XLR (male) + 6.3mm stereo jack Patch', amount: 11, description: 'XLR (male) + 6.3mm stereo jack Patch', price: 0.20, category: 'Cables', detailedDescription: 'Compact 0.9m balanced patch cable with XLR male to 6.3mm stereo TRS jack connectors for connecting mixer buses to outboard processors or converting XLR outputs to TRS inputs.' },
    { id: 'CA-08', name: 'XLR (female) + 6.3mm stereo jack Patch', amount: 9, description: 'XLR (female) + 6.3mm stereo jack Patch', price: 0.20, category: 'Cables', detailedDescription: 'Compact 0.9m balanced patch cable with XLR female to 6.3mm stereo TRS jack connectors for connecting outboard processors back to mixer or converting TRS outputs to XLR inputs.' },
    { 
        id: 'CA-09', 
        name: '6.3 mm jack + 6.3 mm jack', 
        amount: 3,
        price: 0.20,
        description: 'Both sides: 6.3 mm mono jack', 
        category: 'Cables',
        detailedDescription: 'Instrument cable with 6.3mm mono jack connectors on both ends for guitars, basses, keyboards, and effects pedals. Available in 3m and 6m lengths with very good quality construction and flexible black cable.',
        variants: [
            { length: '3m', amount: 3, price: 0.20 },
            { length: '6m', amount: 10, price: 0.30 }
        ]
    },
    { id: 'CA-11', name: 'XLR Patch', amount: 1, description: 'XLR Patch cable / 0.5m', price: 0.40, category: 'Cables', detailedDescription: 'Short 0.5m balanced XLR patch cable with 3-pin XLR male to female connectors for tight patch bay connections, effects routing, and rack equipment wiring.' },
    { id: 'CA-12', name: 'Y-adapter XLR', amount: 3, description: 'Y-adapter XLR (female) to 2x XLR (male) / 0.3m', price: 0.20, category: 'Cables', detailedDescription: 'Short 0.3m Y-adapter cable with one XLR female input splitting to two XLR male outputs for microphone signal distribution or parallel routing.' },
    { id: 'CA-13', name: 'Y-adapter XLR', amount: 1, description: 'Y-adapter XLR (male) to 2x XLR (female) / 0.3m', price: 0.30, category: 'Cables', detailedDescription: 'Short 0.3m Y-adapter cable with one XLR male input splitting to two XLR female outputs for microphone signal distribution or parallel routing.' },
    { id: 'CA-14', name: '3.5mm stereo + 2x XLR', amount: 1, description: 'pro snake BXJ 102-1, Audio Cable with Transformer / 1.5m', price: 1.00, category: 'Cables', detailedDescription: 'Professional 1.5m cable with 3.5mm stereo jack to dual XLR male connectors including integrated transformer for converting consumer-level unbalanced signals to professional balanced outputs.' },
    { id: 'CA-15', name: 'XLR adapter Female-Female', amount: 1, description: 'pro snake TPA 1003 FF / 0.3m', price: 0.20, category: 'Cables', detailedDescription: 'Short 0.3m XLR female to female adapter cable for extending XLR connections or reversing cable direction.' },
    { id: 'CA-16', name: 'XLR adapter Male-Male', amount: 10, description: 'pro snake TPA 1003 MM / 0.3m', price: 0.30, category: 'Cables', detailedDescription: 'Short 0.3m XLR male to male adapter cable for extending XLR connections or reversing cable direction.' },

    { id: 'CA-22', name: 'Multicore Cable - 15m', amount: 1, description: '8-Way Multicore Cable XLR female sockets + XLR male connectors / 15m', price: 5.00, category: 'Cables', detailedDescription: 'Professional 15m 8-way multicore cable with XLR female stage box and 8 XLR male fan-out connectors for clean multi-channel signal routing from stage to mixer.' },
    { id: 'CA-23', name: 'CAT6E - 75m', amount: 2, description: 'CAT6 Ethercon Cable on reel / 75m', price: 7.00, category: 'Cables', detailedDescription: 'Professional 75m CAT6a Ethercon cable on reel for digital audio networking, connecting Allen & Heath digital stageboxes, or Dante/AES67 network audio systems.' },
    
    // Power Distribution
    { id: 'PD-01', name: '3-Way Power Split', amount: 10, description: '3-Outlet power strip', price: 0.20, category: 'Power Distribution' },
    { id: 'PD-02', name: '4-Way Power Split', amount: 7, description: '4-Outlet power strip', price: 0.30, category: 'Power Distribution' },
    { id: 'PD-03', name: '6-Way Power Split', amount: 8, description: '6-Outlet power strip', price: 0.40, category: 'Power Distribution' },
    { id: 'PD-04', name: 'Varytec Power Twist Power Cable 5,0 m', amount: 10, description: 'Power Cable', price: 1.00, category: 'Power Distribution', detailedDescription: 'Professional 5m power cable with 3x1.5mm² wires and Power Twist connector for stage lighting, dimmers, and power distribution systems requiring locking connections.' },
    { 
        id: 'PD-05', 
        name: 'EU Power Cable', 
        amount: 14,
        price: 0.10,
        description: 'EU Power cable', 
        category: 'Power Distribution',
        variants: [
            { length: '1.5m', amount: 14, price: 0.10 },
            { length: '3m', amount: 4, price: 0.20 },
            { length: '5m', amount: 5, price: 0.30 }
        ]
    },
    { 
        id: 'PD-08', 
        name: 'Extension Cable', 
        amount: 12,
        price: 0.30,
        description: 'extension cable', 
        category: 'Power Distribution',
        variants: [
            { length: '5m', amount: 12, price: 0.30 },
            { length: '10m', amount: 4, price: 0.50 },
            { length: '20m', amount: 4, price: 0.70 }
        ]
    },
    { id: 'PD-11', name: 'Varytec Cable Drum IP44 25m 3x 1,5 mm²', amount: 1, description: 'Cable Reel', price: 2.00, category: 'Power Distribution' },
    
    // Accessories - PA Section
    { id: 'AC-PA-01', name: 'Meyer Sound UPA Mounting Yoke', amount: 4, description: 'Adjustable Flying Frame for UPA', price: 4.00, category: 'Accessories' },
    { id: 'AC-PA-02', name: 'Meyer Sound UPA Clamp', amount: 2, description: 'Meyer Sound UPA Clamp', price: 1.00, category: 'Accessories' },
    { id: 'AC-PA-03', name: 'Meyer Sound UPM Mounting Yoke', amount: 4, description: 'Mounting cradle-style yoke for a single UPM1/2P and UPM-1/2XP', price: 4.00, category: 'Accessories' },
    { id: 'AC-PA-04', name: 'K&M 195/8 Black', amount: 2, description: 'Speaker Stand Flange Mount', price: 0.50, category: 'Accessories' },
    { id: 'AC-PA-05', name: 'K&M 66360', amount: 2, description: 'Reducing flange', price: 0.50, category: 'Accessories' },
    { id: 'AC-PA-06', name: 'Gravity SF 36 M10 F Reduce Flange', amount: 4, description: 'Reduction Flange for 35 mm Speaker Stands', price: 0.50, category: 'Accessories' },
    { id: 'AC-PA-07', name: 'K&M 21316', amount: 1, description: 'Travel Bag for speaker and wind-up stands', price: 1.50, category: 'Accessories' },
    { id: 'AC-PA-08', name: 'Stageworx Round Sling WSL-20', amount: 8, description: 'polyester sling WSL-20 1-4.0m / usable length: 0.5-2m / payload: 2000kg', price: 0.50, category: 'Accessories' },
    { id: 'AC-PA-09', name: 'Stairville Shackle', amount: 16, description: 'Shackle / 0.75-2.0 t', price: 0.20, category: 'Accessories' },
    
    // Accessories - Studio/Speaker Section
    { id: 'AC-SP-01', name: 'Genelec GLM Set', amount: 1, description: 'Calibration System and DSP Control', price: 5.00, category: 'Accessories', detailedDescription: 'Professional acoustic calibration system including GLM 8300A network interface, 8300-601 measurement microphone, and GLM software for automatic room optimization of Genelec Smart Active Monitoring systems.' },
    { id: 'AC-SP-02', name: 'Genelec Z8030-408', amount: 2, description: 'Tripod Adapter', price: 0.50, category: 'Accessories', detailedDescription: 'Stand adapter for mounting Genelec 8030 series monitors on standard microphone stands with 3/8" thread.' },
    { id: 'AC-SP-03', name: 'Genelec 8000-422W Wall Mount', amount: 2, description: 'Wall Mount for Genelec 8330A', price: 0.50, category: 'Accessories' },
    { id: 'AC-SP-04', name: 'Fostex EB6301 Wall Mounting', amount: 10, description: 'Wall/Stand Mount for Fostex 6301B', price: 1.00, category: 'Accessories', detailedDescription: 'Mounting bracket for Fostex 6301B speakers enabling wall mounting or microphone stand attachment for flexible multichannel speaker positioning.' },
    
    // Accessories - Mixer Section
    { id: 'AC-MX-01', name: 'Allen & Heath Carry Bag QU 16', amount: 1, description: 'Carry Bag for Allen & Heath QU 16', price: 5.00, category: 'Accessories', detailedDescription: 'Padded transport bag designed for Allen & Heath QU-16 digital mixer with compartments for cables and accessories.' },
    { id: 'AC-MX-02', name: 'Flightcase Allen & Heath QU16', amount: 1, description: 'flightcase for Allen & Heath QU16', price: 6.00, category: 'Accessories' },
    { id: 'AC-MX-03', name: 'Allen & Heath SQ5 Dust Cover', amount: 1, description: 'Dust and Dirt Cover', price: 1.00, category: 'Accessories' },
    { id: 'AC-MX-04', name: 'Decksaver Allen & Heath QU16', amount: 1, description: 'Dust cover for Allen & Heath QU16', price: 3.00, category: 'Accessories' },
    { id: 'AC-MX-05', name: 'Allen & Heath LEDLamp X', amount: 1, description: 'Gooseneck Lamp', price: 2.00, category: 'Accessories' },
    { id: 'AC-MX-06', name: 'Thon Rack 3U Eco II Compact 23', amount: 1, description: '19" Economy Case', price: 3.00, category: 'Accessories' },
    
    // Accessories - Microphone Section
    { id: 'AC-MI-01', name: 'DAP ACA-MIC5 Pro', amount: 1, description: 'microphone flight case with space for 12 microphones and accessories', price: 1.00, category: 'Accessories' },
    { id: 'AC-MI-02', name: 'K&M 23550 Microphone Stereo Bar', amount: 3, description: 'Stereo Bar', price: 0.30, category: 'Accessories', detailedDescription: 'Adjustable stereo bar for mounting two microphones on single stand for X/Y, ORTF, or spaced stereo recording techniques.' },
    { id: 'AC-MI-03', name: 'Uši Windbubble', amount: 2, description: 'Wind protection', price: 0.50, category: 'Accessories' },
    { id: 'AC-MI-04', name: 'Rycote Super Shield Kit Large', amount: 1, description: 'Wind shield pod with adjustable shock-mount handle and windjammer', price: 10.00, category: 'Accessories', detailedDescription: 'Professional windscreen system with Lyre shock mount for 250-300mm shotgun microphones, including 450mm windscreen, longhair windjammer, XLR cable, and brush for outdoor recording and film production.' },
    { id: 'AC-MI-05', name: 'Millenium 6-Micstand Bag', amount: 2, description: 'Gig Bag For Up To 6 Microphone Stand', price: 1.00, category: 'Accessories', detailedDescription: 'Transport bag for up to 6 microphone stands, 100cm deep with 30cm diameter, internal dividers, and water-repellent construction for touring and storage.' },
    { id: 'AC-MI-06', name: 'Flyht Pro Gorilla Bag SB-S', amount: 1, description: 'Transport bag for up to six microphone stands', price: 1.00, category: 'Accessories', detailedDescription: 'Padded transport bag for up to 6 mic stands with 10mm padding, foldable divider, water-resistant Cordura material, suitable for stands up to 700mm height.' },
    { id: 'AC-MI-07', name: 'Digital Sound 8930B', amount: 1, description: 'Portable Sound Level Calibrator', price: 2.50, category: 'Accessories' },
    
    // Accessories - General
    { id: 'AC-01', name: 'Manfrotto MCLAMP Smartphone Holder', amount: 1, description: 'mini tripod', price: 0.50, category: 'Accessories' },
    { id: 'AC-02', name: 'Manfrotto Smartphone Clamp', amount: 1, description: 'Smartphone Clamp', price: 0.20, category: 'Accessories' },
    { id: 'AC-03', name: 'Swissonic Quadphone', amount: 1, description: '4-Channel Headphone Amplifier', price: 1.00, category: 'Accessories' },
    { id: 'AC-04', name: 'ADJ Fog Fury 3000', amount: 1, description: '1500W DMX Fog Machine', price: 8.00, category: 'Accessories', detailedDescription: 'Professional 1500W DMX fog machine with 21000 cu.ft/min output, 5L tank, ETS technology, 3 operational modes (Manual/Timer/DMX), and LED heating indicators for stage productions and events.' },
    { id: 'AC-05', name: 'Sennheiser HD-25', amount: 1, description: 'Professional DJ headphones', price: 5.00, category: 'Accessories', detailedDescription: 'Professional closed on-ear DJ headphones with 70 Ohm impedance, 16-22000 Hz frequency range, swiveling earcup, replaceable cable, 140g weight, industry-standard for monitoring and DJing.' },
    { id: 'AC-06', name: 'Behringer CT100', amount: 1, description: 'Cable Tester', price: 1.00, category: 'Accessories', detailedDescription: 'Professional 6-in-1 cable tester for XLR, jack, RCA, and MIDI cables with continuity check, phantom power detection, test tone generator, and LED indicators, battery-powered for portable testing.' },
];
